rules:
  force-pseudo-nesting: 0
  leading-zero: 0
  class-name-format:
    - 2
    -
      convention: 'camelcase'
  no-color-literals:
    - 2
    -
      allow-rgba: true
  no-transition-all:
    - 0
  property-units:
    - 2
    -
      global: ['rem', 'vw', 's', 'vh', 'vmin', 'vmax']
